# HeadDropPlugin config

head-drop:
  # Название головы (%player% заменится на имя жертвы)
  head-name: "&cГолова %player%"
  # Описание головы
  head-lore:
    - "&7Отрублена топором"
    - "&7Игрок: %player%"