# HeadDropPlugin config

head-drop:
  # время в секундах, через сколько голова пропадет после падения
  despawn-time: 30

  # Название головы (%player% заменится на имя жертвы)
  head-name: "&cГолова %player%"
  # Описание головы
  head-lore:
    - "&7Отрублена топором"
    - "&7Игрок: %player%"