name: DropAHead
version: '1.1'
main: net.lr1ne.Main
api-version: 1.21
author: [lr1ne]
website: https://modrinth.com/plugin/dropahead
commands:
  dap:
    description: Reloads the DropAHead configuration
    usage: /<command> reload
    aliases:
      - dropahead
permissions:
  dropahead.reload:
    description: Allows reloading the DropAHead configuration
    default: op
